### ISSUE TITLE
Bug with cpu count on windows machine

### ISSUE THREAD

**Issue by VermaSh** [AdoptOpenJDK/openjdk-jenkins-helper#6]
For windows systems there is a bug with the script that updates the CPU count system variable. Even though the machine has 8 cores the system variable reports only 2.

**Comment by gdams** [comment]
closing as this fixed

**Comment by VermaSh** [comment]
@gdams what was the fix?

**Comment by gdams** [comment]
sorry I didn't mean to close this. wrong repo 🥇

**Comment by VermaSh** [comment]
no worries, wrong repo myself
